### PR TITLE
Update for release 2.6

### PR DESCRIPTION
**Pull request by eemurphy**
Signed-off-by: Erin Murphy <erinmurp@redhat.com>

Issue: https://github.com/stolostron/backlog/issues/22278

### CODE REVIEW

**Review by chenz4027 — APPROVED** [review]
lgtm

**Comment by KevinFCormier** [comment]
@JakobGray @chenz4027 We don't ship this chart anymore, right? Should we mark the repo as deprecated?

**Comment by JakobGray** [comment]
@KevinFCormier Yeah let's label it as deprecated. I'll make a note to take it out of the repo.

**Comment by KevinFCormier** [comment]
image

Description is updated. I suppose we could also update the README.

**Pull request merged**
